### ISSUE TITLE
Home Assistant - Entity is non-numeric

### ISSUE THREAD

**Issue by Mieliebom** [freakstatic/node-temperature-mqtt#1]
Hi

Thank you for an awesome solution!

I have the powershell running and publishing numbers to mqtt. I can see values in console for CPU thread 0 and Graphic card 0. It makes a successful connection to mqtt and I can see the CPU 0 value on Home Assistant/lovelace. 

My issue is that I am not seeing the GPU value - the card only gives the error that the "Entity is non-numeric". Please let me know how you got around this?

Thanks!

**Comment by freakstatic** [comment]
Hi! 
Thanks for trying this project! 😁
What graphic card do you have?

**Comment by Mieliebom** [comment]
Thx for the quick reply! I'm using an nvidia 1660. I can see values for it on the console:
![image](https://user-images.githubusercontent.com/65774948/89423546-ecd7e880-d736-11ea-8541-01f1ff036e3f.png)

![image](https://user-images.githubusercontent.com/65774948/89424004-7f788780-d737-11ea-88c6-bc9f93f4af08.png)

**Comment by freakstatic** [comment]
Hum the problem seems to be in the home assistant configuration...
Can you show me your configuration?

**Comment by Mieliebom** [comment]
Here's my configuration.yml:


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: mqtt
    state_topic: 'computer/temperatures/cpu/0'
    name: 'CPU - Thread 0'
    unit_of_measurement: '  C'

  - platform: mqtt
    state_topic: 'computer/temperatures/cpu/1'
    name: 'CPU - Thread 1'
    unit_of_measurement: '  C'

  - platform: mqtt
    state_topic: 'computer/temperatures/cpu/2'
    name: 'CPU - Thread 2'
    unit_of_measurement: '  C'

  - platform: mqtt
    state_topic: 'computer/temperatures/cpu/3'
    name: 'CPU - Thread 3'
    unit_of_measurement: '  C'

  - platform: mqtt
    state_topic: 'computer/temperatures/cpu/4'
    name: 'CPU - Thread 4'
    unit_of_measurement: '  C'

  - platform: mqtt
    state_topic: 'computer/temperatures/cpu/5'
    name: 'CPU - Thread 5'
    unit_of_measurement: '  C'

  - platform: mqtt
    state_topic: 'computer/temperatures/graphic-card/1'
    name: 'Graphic Card'
    unit_of_measurement: '  C'

**Comment by freakstatic** [comment]
What Home Assistant version do you have?

**Comment by Mieliebom** [comment]
Home Assistant 0.113.3


arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.126-v8
python_version | 3.8.3
supervisor | 230
timezone | Africa/Johannesburg
version | 0.113.3
virtualenv | false

**Comment by Mieliebom** [comment]
I do believe it is a known issue in Hassio, just very strange that one metric will display but the other wont

**Comment by freakstatic** [comment]
Are you using the "/1" in the state_topic for some reason?
Do you have two graphic cards?

It probably should look like this, if you only have 1 graphic card:
```
platform: mqtt
state_topic: 'computer/temperatures/graphic-card/0'
name: 'Graphic Card'
unit_of_measurement: ' C'
```

**Comment by Mieliebom** [comment]
Aaahh I feel so stupid for missing that! Works perfectly, thanks!!!
